<?php
include_once("Net/HL7/Types/CE.php");
include_once("Net/HL7/Types/CQ.php");
include_once("Net/HL7/Types/CWE.php");
include_once("Net/HL7/Types/CX.php");
include_once("Net/HL7/Types/ED.php");
include_once("Net/HL7/Types/EI.php");
include_once("Net/HL7/Types/EIP.php");
include_once("Net/HL7/Types/FN.php");
include_once("Net/HL7/Types/HD.php");
include_once("Net/HL7/Types/MSG.php");
include_once("Net/HL7/Types/PL.php");
include_once("Net/HL7/Types/PRL.php");
include_once("Net/HL7/Types/PT.php");
include_once("Net/HL7/Types/RP.php");
include_once("Net/HL7/Types/SAD.php");
include_once("Net/HL7/Types/SN.php");
include_once("Net/HL7/Types/TS.php");
include_once("Net/HL7/Types/VID.php");
include_once("Net/HL7/Types/XAD.php");
include_once("Net/HL7/Types/XCN.php");
include_once("Net/HL7/Types/XON.php");
include_once("Net/HL7/Types/XPN.php");
?>
